### ISSUE TITLE
Error running simple_example

### ISSUE THREAD

**Issue by baumbude** [flixOpt/flixOpt#80]
simple_example wirft folgenden Fehler:
(Python 3.9, all requirements installed)

```
2024-11-28 15:53:24 - INFO     : Investment Decisions:
2024-11-28 15:53:24 - INFO     :   Storage                       :      30.00
2024-11-28 15:53:24 - INFO     : ############################# End of Main Results ##############################
Traceback (most recent call last):
  File "C:\Repos\flixOpt\examples\Ex01_simple\simple_example.py", line 88, in <module>
    calculation.solve(fx.solvers.HighsSolver(), save_results=True)
  File "C:\Repos\flixOpt\flixOpt\calculation.py", line 159, in solve
    self._save_solve_infos()
  File "C:\Repos\flixOpt\flixOpt\calculation.py", line 99, in _save_solve_infos
    nodes_info, edges_info = self.flow_system.network_infos()
  File "C:\Repos\flixOpt\flixOpt\flow_system.py", line 92, in network_infos
    nodes = {node.label_full: {'label': node.label,
  File "C:\Repos\flixOpt\flixOpt\flow_system.py", line 94, in <dictcomp>
    'infos':  node.__str__()}
  File "C:\Repos\flixOpt\flixOpt\structure.py", line 272, in __str__
    return get_object_infos_as_str(self)
  File "C:\Repos\flixOpt\flixOpt\structure.py", line 547, in get_object_infos_as_str
    details.append(f"{name}={item_as_str(value)}")  # Formatted numeric-string
  File "C:\Repos\flixOpt\flixOpt\structure.py", line 526, in item_as_str
    elif isinstance(item, (Numeric, TimeSeries, TimeSeriesData)):
  File "C:\Program Files\Python39\lib\typing.py", line 657, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "C:\Program Files\Python39\lib\typing.py", line 660, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

**Comment by FBumann** [comment]
Mit dem aktuellsten pull vom dev?

Bei mir läuft alles.
Aber mit Python 3.10.
Unabhängig von dem Fehler hier ist Python 3.10 die Mindestanforderung. Steht auch so in setup.py!


```
/Users/felix/Documents/Dokumente-eigene/Code/flixOpt/.venv/bin/python /Users/felix/Documents/Dokumente-eigene/Code/flixOpt/examples/Ex01_simple/simple_example.py 
2024-11-28 19:32:05 - INFO     : Registered new Effect: costs
2024-11-28 19:32:05 - INFO     : Registered new Effect: CO2
2024-11-28 19:32:05 - INFO     : Registered new Component: Boiler
2024-11-28 19:32:05 - INFO     : Registered new Component: Storage
2024-11-28 19:32:05 - INFO     : Registered new Component: CHP
2024-11-28 19:32:05 - INFO     : Registered new Component: Heat Demand
2024-11-28 19:32:05 - INFO     : Registered new Component: Gastarif
2024-11-28 19:32:05 - INFO     : Registered new Component: Einspeisung
2024-11-28 19:32:05 - INFO     : ############################### starting solving ###############################
2024-11-28 19:32:05 - INFO     : No. of Equations   (single): 45 (157)
2024-11-28 19:32:05 - INFO     : No. of Inequations (single): 7 (65)
2024-11-28 19:32:05 - INFO     : No. of Variables   (single): 57 (266)
2024-11-28 19:32:06 - INFO     : Termination message: "Not Implemented for HighsSolver yet"
2024-11-28 19:32:06 - INFO     : ############################### finished solving ###############################
2024-11-28 19:32:06 - INFO     : ################################# Main Results #################################
2024-11-28 19:32:06 - INFO     : costs [€]:
2024-11-28 19:32:06 - INFO     :   operation      :      63.88
2024-11-28 19:32:06 - INFO     :   invest         :      20.00
2024-11-28 19:32:06 - INFO     :   sum            :      83.88
2024-11-28 19:32:06 - INFO     : CO2 [kg]:
2024-11-28 19:32:06 - INFO     :   operation      :     255.33
2024-11-28 19:32:06 - INFO     :   invest         :      -0.00
2024-11-28 19:32:06 - INFO     :   sum            :     255.33
2024-11-28 19:32:06 - INFO     : penalty          :       0.00
2024-11-28 19:32:06 - INFO     : --------------------------------------------------------------------------------
2024-11-28 19:32:06 - INFO     : Objective        :      83.88
2024-11-28 19:32:06 - INFO     : --------------------------------------------------------------------------------
2024-11-28 19:32:06 - INFO     : Investment Decisions:
2024-11-28 19:32:06 - INFO     :   Storage                       :      30.00
2024-11-28 19:32:06 - INFO     : ############################# End of Main Results ##############################
2024-11-28 19:32:06 - INFO     : ################################################################################
2024-11-28 19:32:06 - INFO     : ########################### Saved Calculation: Sim1 ############################
2024-11-28 19:32:06 - INFO     : ################################################################################
2024-11-28 19:32:06 - INFO     : Saving calculation to .json took     0.01 seconds
2024-11-28 19:32:06 - INFO     : Saving calculation to .yaml took     0.03 seconds
2024-11-28 19:32:06 - INFO     : Loading Calculation Infos from .yaml took     0.02 seconds
2024-11-28 19:32:06 - INFO     : Loading results from .json took     0.00 seconds
2024-11-28 19:32:06 - INFO     : Loading data from .json took     0.00 seconds
```

**Comment by FBumann** [comment]
Habs.
Liegt an python 3.9
Das typing zeug ist seit 3.10 nochmal deutlich besser und kann mehr.
Habe das genutzt.
mit python 3.9 bekomme ich auch
```
/Users/felix/Documents/Dokumente-eigene/Code/PythonProject1/.venv/bin/python /Users/felix/Documents/Dokumente-eigene/Code/PythonProject1/simple_example-2.py 
2024-11-28 19:37:43 - INFO     : Registered new Effect: costs
2024-11-28 19:37:43 - INFO     : Registered new Effect: CO2
2024-11-28 19:37:43 - INFO     : Registered new Component: Boiler
2024-11-28 19:37:43 - INFO     : Registered new Component: Storage
2024-11-28 19:37:43 - INFO     : Registered new Component: CHP
2024-11-28 19:37:43 - INFO     : Registered new Component: Heat Demand
2024-11-28 19:37:43 - INFO     : Registered new Component: Gastarif
2024-11-28 19:37:43 - INFO     : Registered new Component: Einspeisung
Traceback (most recent call last):
  File "/Users/felix/Documents/Dokumente-eigene/Code/PythonProject1/simple_example-2.py", line 80, in <module>
    flow_system.visualize_network()
  File "/Users/felix/Documents/Dokumente-eigene/Code/PythonProject1/.venv/lib/python3.9/site-packages/flixOpt/flow_system.py", line 157, in visualize_network
    node_infos, edge_infos = self.network_infos()
  File "/Users/felix/Documents/Dokumente-eigene/Code/PythonProject1/.venv/lib/python3.9/site-packages/flixOpt/flow_system.py", line 92, in network_infos
    nodes = {node.label_full: {'label': node.label,
  File "/Users/felix/Documents/Dokumente-eigene/Code/PythonProject1/.venv/lib/python3.9/site-packages/flixOpt/flow_system.py", line 94, in <dictcomp>
    'infos':  node.__str__()}
  File "/Users/felix/Documents/Dokumente-eigene/Code/PythonProject1/.venv/lib/python3.9/site-packages/flixOpt/structure.py", line 272, in __str__
    return get_object_infos_as_str(self)
  File "/Users/felix/Documents/Dokumente-eigene/Code/PythonProject1/.venv/lib/python3.9/site-packages/flixOpt/structure.py", line 547, in get_object_infos_as_str
    details.append(f"{name}={item_as_str(value)}")  # Formatted numeric-string
  File "/Users/felix/Documents/Dokumente-eigene/Code/PythonProject1/.venv/lib/python3.9/site-packages/flixOpt/structure.py", line 526, in item_as_str
    elif isinstance(item, (Numeric, TimeSeries, TimeSeriesData)):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 720, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 723, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```


Numeric wird nicht richtig verwendet im check, da 3.9 das nicht nicht kann.
```
    elif isinstance(item, (Numeric, TimeSeries, TimeSeriesData)):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 720, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/Library/Frameworks/Python.framework/V
```

# TODO
Update setup.py auf >=3.10

**Comment by FBumann** [comment]
3.10 gibts auch schon seit 2021-10-04
[https://www.python.org/downloads/](https://www.python.org/downloads/)

**Comment by baumbude** [comment]
> ... Steht auch so in setup.py!
ja, jetzt steht es da ;)

**Comment by FBumann** [comment]
> > ... Steht auch so in setup.py!
> > ja, jetzt steht es da ;)

Ja, das war nicht korrekt ;)
